language: elixir
services:
  - mysql

env:
  - MIX_ENV=travis

install:
  - mix local.rebar --force
  - mix local.hex --force --no-check-certificate
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

cache:
  directories:
    - _build
    - deps
